# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Noctambus' do
pod ‘Parse’
pod ‘ParseUI’
pod ‘Alamofire’
pod ’SwiftyJSON’
pod ’KVNProgress'
end

target 'NoctambusTests' do

end

